// Script Ä‘á»ƒ thÃªm 100 cÃ¢u há»i FAQ bá»• sung cho chatbot
const mongoose = require('mongoose');
require('dotenv').config();

// Káº¿t ná»‘i MongoDB
mongoose
    .connect(process.env.MONGO_URI)
    .then(() => console.log('MongoDB connected'))
    .catch((err) => console.log('MongoDB connection error:', err));

const FAQ = require('./src/models/faq.model');

const additionalFAQs = [
    // CÃ¢u há»i vá» sáº£n pháº©m vÃ  tÃ¬m kiáº¿m (1-20)
    {
        question: 'LÃ m sao Ä‘á»ƒ xem chi tiáº¿t má»™t cuá»‘n sÃ¡ch?',
        answer: 'Báº¡n chá»‰ cáº§n click vÃ o hÃ¬nh áº£nh hoáº·c tÃªn sÃ¡ch Ä‘á»ƒ xem thÃ´ng tin chi tiáº¿t bao gá»“m: mÃ´ táº£, tÃ¡c giáº£, nhÃ  xuáº¥t báº£n, nÄƒm xuáº¥t báº£n, giÃ¡ thuÃª vÃ  tÃ¬nh tráº¡ng sÃ¡ch.',
        keywords: ['xem chi tiáº¿t', 'thÃ´ng tin sÃ¡ch', 'mÃ´ táº£ sÃ¡ch', 'detail'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'SÃ¡ch nÃ o Ä‘ang Ä‘Æ°á»£c thuÃª nhiá»u nháº¥t?',
        answer: 'Báº¡n cÃ³ thá»ƒ xem danh sÃ¡ch sÃ¡ch phá»• biáº¿n trÃªn trang chá»§ hoáº·c sáº¯p xáº¿p theo "ÄÆ°á»£c thuÃª nhiá»u nháº¥t" khi tÃ¬m kiáº¿m. Nhá»¯ng cuá»‘n sÃ¡ch nÃ y thÆ°á»ng cÃ³ cháº¥t lÆ°á»£ng vÃ  ná»™i dung háº¥p dáº«n.',
        keywords: ['sÃ¡ch hot', 'phá»• biáº¿n', 'Ä‘Æ°á»£c thuÃª nhiá»u', 'trending'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch má»›i phÃ¡t hÃ nh khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i thÆ°á»ng xuyÃªn cáº­p nháº­t sÃ¡ch má»›i. Báº¡n cÃ³ thá»ƒ xem má»¥c "SÃ¡ch má»›i" trÃªn trang chá»§ hoáº·c sáº¯p xáº¿p theo "Má»›i nháº¥t" khi tÃ¬m kiáº¿m.',
        keywords: ['sÃ¡ch má»›i', 'new books', 'phÃ¡t hÃ nh má»›i', 'cáº­p nháº­t'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'TÃ´i cÃ³ thá»ƒ xem trÆ°á»›c ná»™i dung sÃ¡ch khÃ´ng?',
        answer: 'Má»™t sá»‘ cuá»‘n sÃ¡ch cÃ³ chá»©c nÄƒng xem trÆ°á»›c vÃ i trang Ä‘áº§u. Báº¡n hÃ£y kiá»ƒm tra trong trang chi tiáº¿t sÃ¡ch, náº¿u cÃ³ nÃºt "Xem trÆ°á»›c" báº¡n cÃ³ thá»ƒ click Ä‘á»ƒ Ä‘á»c thá»­.',
        keywords: ['xem trÆ°á»›c', 'preview', 'Ä‘á»c thá»­', 'sample'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'LÃ m tháº¿ nÃ o Ä‘á»ƒ tÃ¬m sÃ¡ch theo tÃ¡c giáº£?',
        answer: 'Báº¡n cÃ³ thá»ƒ gÃµ tÃªn tÃ¡c giáº£ vÃ o thanh tÃ¬m kiáº¿m hoáº·c click vÃ o tÃªn tÃ¡c giáº£ trong trang chi tiáº¿t sÃ¡ch Ä‘á»ƒ xem táº¥t cáº£ sÃ¡ch cá»§a tÃ¡c giáº£ Ä‘Ã³.',
        keywords: ['tÃ¬m tÃ¡c giáº£', 'search author', 'sÃ¡ch cá»§a tÃ¡c giáº£'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch tiáº¿ng Anh khÃ´ng?',
        answer: 'CÃ³, thÆ° viá»‡n chÃºng tÃ´i cÃ³ nhiá»u Ä‘áº§u sÃ¡ch tiáº¿ng Anh trong cÃ¡c lÄ©nh vá»±c khÃ¡c nhau. Báº¡n cÃ³ thá»ƒ lá»c theo ngÃ´n ngá»¯ hoáº·c tÃ¬m kiáº¿m vá»›i tá»« khÃ³a "English book".',
        keywords: ['sÃ¡ch tiáº¿ng anh', 'english book', 'foreign book', 'ngoáº¡i ngá»¯'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'ThÆ° viá»‡n cÃ³ sÃ¡ch giÃ¡o khoa khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ bá»™ sÆ°u táº­p sÃ¡ch giÃ¡o khoa tá»« lá»›p 1 Ä‘áº¿n lá»›p 12 vÃ  cáº£ sÃ¡ch giÃ¡o trÃ¬nh Ä‘áº¡i há»c. Báº¡n cÃ³ thá»ƒ tÃ¬m trong danh má»¥c "GiÃ¡o dá»¥c".',
        keywords: ['sÃ¡ch giÃ¡o khoa', 'textbook', 'sÃ¡ch há»c', 'giÃ¡o trÃ¬nh'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch thiáº¿u nhi cho tráº» em khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ ráº¥t nhiá»u sÃ¡ch thiáº¿u nhi phÃ¹ há»£p vá»›i nhiá»u Ä‘á»™ tuá»•i khÃ¡c nhau. Báº¡n cÃ³ thá»ƒ xem trong danh má»¥c "Thiáº¿u nhi" hoáº·c lá»c theo Ä‘á»™ tuá»•i.',
        keywords: ['sÃ¡ch thiáº¿u nhi', 'children book', 'sÃ¡ch tráº» em', 'kid book'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'LÃ m sao biáº¿t sÃ¡ch cÃ²n hay háº¿t?',
        answer: 'TrÃªn trang chi tiáº¿t sÃ¡ch sáº½ hiá»ƒn thá»‹ tráº¡ng thÃ¡i "CÃ²n hÃ ng" hoáº·c "Háº¿t hÃ ng". Náº¿u háº¿t hÃ ng, báº¡n cÃ³ thá»ƒ Ä‘Äƒng kÃ½ nháº­n thÃ´ng bÃ¡o khi sÃ¡ch cÃ³ láº¡i.',
        keywords: ['tÃ¬nh tráº¡ng sÃ¡ch', 'cÃ²n hÃ ng', 'háº¿t hÃ ng', 'availability'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ Ä‘áº·t trÆ°á»›c sÃ¡ch Ä‘ang Ä‘Æ°á»£c thuÃª khÃ´ng?',
        answer: 'Hiá»‡n táº¡i chÆ°a há»— trá»£ tÃ­nh nÄƒng Ä‘áº·t trÆ°á»›c. Báº¡n cÃ³ thá»ƒ thÃªm sÃ¡ch vÃ o danh sÃ¡ch yÃªu thÃ­ch vÃ  kiá»ƒm tra láº¡i sau. ChÃºng tÃ´i sáº½ cáº­p nháº­t tÃ­nh nÄƒng nÃ y trong tÆ°Æ¡ng lai.',
        keywords: ['Ä‘áº·t trÆ°á»›c', 'pre-order', 'book ahead', 'reserve'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ thuÃª bá»™ sÃ¡ch khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ thuÃª nhiá»u cuá»‘n sÃ¡ch cÃ¹ng lÃºc. Chá»‰ cáº§n thÃªm táº¥t cáº£ cÃ¡c cuá»‘n vÃ o giá» hÃ ng vÃ  thanh toÃ¡n má»™t láº§n.',
        keywords: ['bá»™ sÃ¡ch', 'nhiá»u sÃ¡ch', 'thuÃª nhiá»u', 'set book'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ giá»›i háº¡n sá»‘ lÆ°á»£ng sÃ¡ch Ä‘Æ°á»£c thuÃª khÃ´ng?',
        answer: 'Má»—i tÃ i khoáº£n cÃ³ thá»ƒ thuÃª tá»‘i Ä‘a 10 cuá»‘n sÃ¡ch cÃ¹ng lÃºc. Náº¿u báº¡n cáº§n thuÃª nhiá»u hÆ¡n, vui lÃ²ng liÃªn há»‡ vá»›i chÃºng tÃ´i Ä‘á»ƒ Ä‘Æ°á»£c há»— trá»£.',
        keywords: ['giá»›i háº¡n', 'sá»‘ lÆ°á»£ng tá»‘i Ä‘a', 'limit', 'maximum'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» láº­p trÃ¬nh khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u sÃ¡ch vá» láº­p trÃ¬nh vÃ  cÃ´ng nghá»‡ nhÆ° Python, Java, JavaScript, AI, Machine Learning vÃ  nhiá»u chá»§ Ä‘á» khÃ¡c. Xem trong danh má»¥c "CÃ´ng nghá»‡".',
        keywords: ['sÃ¡ch láº­p trÃ¬nh', 'programming', 'coding', 'tech book'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» kinh doanh khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ bá»™ sÆ°u táº­p phong phÃº vá» kinh doanh, khá»Ÿi nghiá»‡p, quáº£n trá»‹, marketing, tÃ i chÃ­nh vÃ  cÃ¡c lÄ©nh vá»±c liÃªn quan. Xem trong danh má»¥c "Kinh táº¿".',
        keywords: ['sÃ¡ch kinh doanh', 'business book', 'startup', 'quáº£n trá»‹'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ truyá»‡n tranh khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u bá»™ truyá»‡n tranh ná»•i tiáº¿ng cá»§a Nháº­t Báº£n, HÃ n Quá»‘c vÃ  Viá»‡t Nam. Báº¡n cÃ³ thá»ƒ tÃ¬m trong danh má»¥c "Truyá»‡n tranh/Manga".',
        keywords: ['truyá»‡n tranh', 'manga', 'comic', 'manhwa'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ light novel khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u light novel Ä‘Æ°á»£c dá»‹ch tá»« tiáº¿ng Nháº­t vÃ  tiáº¿ng Trung. Báº¡n cÃ³ thá»ƒ tÃ¬m kiáº¿m vá»›i tá»« khÃ³a "light novel" hoáº·c xem trong danh má»¥c "VÄƒn há»c".',
        keywords: ['light novel', 'tiá»ƒu thuyáº¿t nháº¹', 'novel', 'ln'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» tÃ¢m lÃ½ há»c khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u sÃ¡ch vá» tÃ¢m lÃ½ há»c, phÃ¡t triá»ƒn báº£n thÃ¢n, ká»¹ nÄƒng sá»‘ng vÃ  sá»©c khá»e tinh tháº§n. Xem trong danh má»¥c tÆ°Æ¡ng á»©ng.',
        keywords: ['sÃ¡ch tÃ¢m lÃ½', 'psychology', 'phÃ¡t triá»ƒn báº£n thÃ¢n', 'self-help'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ Ä‘Ã¡nh giÃ¡ sÃ¡ch?',
        answer: 'Sau khi tráº£ sÃ¡ch, báº¡n cÃ³ thá»ƒ vÃ o lá»‹ch sá»­ thuÃª sÃ¡ch Ä‘á»ƒ Ä‘Ã¡nh giÃ¡ vÃ  nháº­n xÃ©t vá» cuá»‘n sÃ¡ch. ÄÃ¡nh giÃ¡ cá»§a báº¡n giÃºp ngÆ°á»i khÃ¡c tham kháº£o khi chá»n sÃ¡ch.',
        keywords: ['Ä‘Ã¡nh giÃ¡', 'review', 'rating', 'comment'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ xem Ä‘Ã¡nh giÃ¡ cá»§a ngÆ°á»i khÃ¡c khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ xem Ä‘Ã¡nh giÃ¡ vÃ  nháº­n xÃ©t cá»§a ngÆ°á»i dÃ¹ng khÃ¡c trong trang chi tiáº¿t sÃ¡ch, pháº§n "ÄÃ¡nh giÃ¡ & Nháº­n xÃ©t".',
        keywords: ['xem review', 'Ä‘Ã¡nh giÃ¡ ngÆ°á»i khÃ¡c', 'feedback', 'comments'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» lá»‹ch sá»­ Viá»‡t Nam khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u sÃ¡ch vá» lá»‹ch sá»­ Viá»‡t Nam tá»« cá»• Ä‘áº¡i Ä‘áº¿n hiá»‡n Ä‘áº¡i, bao gá»“m cáº£ sÃ¡ch há»c thuáº­t vÃ  sÃ¡ch Ä‘áº¡i chÃºng. Xem trong danh má»¥c "Lá»‹ch sá»­".',
        keywords: ['lá»‹ch sá»­ viá»‡t nam', 'history', 'sá»­ viá»‡t', 'vietnam history'],
        category: 'product',
        isActive: true,
    },

    // CÃ¢u há»i vá» thanh toÃ¡n vÃ  giÃ¡ cáº£ (21-35)
    {
        question: 'CÃ³ thá»ƒ thanh toÃ¡n khi nháº­n sÃ¡ch khÃ´ng?',
        answer: 'Hiá»‡n táº¡i chÃºng tÃ´i chÆ°a há»— trá»£ thanh toÃ¡n khi nháº­n hÃ ng (COD). Báº¡n cáº§n thanh toÃ¡n trá»±c tuyáº¿n trÆ°á»›c khi nháº­n sÃ¡ch.',
        keywords: ['cod', 'thanh toÃ¡n khi nháº­n', 'ship cod', 'payment on delivery'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'Khi nÃ o tiá»n cá»c Ä‘Æ°á»£c hoÃ n láº¡i?',
        answer: 'Tiá»n cá»c sáº½ Ä‘Æ°á»£c hoÃ n láº¡i trong vÃ²ng 3-5 ngÃ y lÃ m viá»‡c sau khi báº¡n tráº£ sÃ¡ch vÃ  chÃºng tÃ´i xÃ¡c nháº­n sÃ¡ch khÃ´ng bá»‹ hÆ° há»ng.',
        keywords: ['hoÃ n cá»c', 'refund deposit', 'tráº£ tiá»n cá»c'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'CÃ³ phÃ­ giao hÃ ng khÃ´ng?',
        answer: 'Miá»…n phÃ­ giao hÃ ng cho Ä‘Æ¡n tá»« 50,000â‚« trong ná»™i thÃ nh. ÄÆ¡n hÃ ng dÆ°á»›i 50,000â‚« vÃ  khu vá»±c ngoáº¡i thÃ nh sáº½ cÃ³ phÃ­ váº­n chuyá»ƒn tÃ¹y khoáº£ng cÃ¡ch.',
        keywords: ['phÃ­ ship', 'phÃ­ giao hÃ ng', 'shipping fee', 'delivery cost'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'GiÃ¡ thuÃª sÃ¡ch cÃ³ bao gá»“m thuáº¿ khÃ´ng?',
        answer: 'GiÃ¡ hiá»ƒn thá»‹ trÃªn website Ä‘Ã£ bao gá»“m thuáº¿ VAT. Báº¡n sáº½ nháº­n Ä‘Æ°á»£c hÃ³a Ä‘Æ¡n Ä‘iá»‡n tá»­ sau khi thanh toÃ¡n.',
        keywords: ['thuáº¿', 'vat', 'tax', 'giÃ¡ Ä‘Ã£ thuáº¿'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'CÃ³ Ä‘Æ°á»£c hoÃ n tiá»n khÃ´ng?',
        answer: 'HoÃ n tiá»n chá»‰ Ã¡p dá»¥ng trong trÆ°á»ng há»£p: sÃ¡ch bá»‹ lá»—i, sÃ¡ch giao sai, hoáº·c há»§y Ä‘Æ¡n trong vÃ²ng 24h sau khi Ä‘áº·t. Vui lÃ²ng liÃªn há»‡ vá»›i chÃºng tÃ´i Ä‘á»ƒ Ä‘Æ°á»£c há»— trá»£.',
        keywords: ['hoÃ n tiá»n', 'refund', 'money back', 'tráº£ láº¡i tiá»n'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'TÃ´i cÃ³ thá»ƒ thay Ä‘á»•i phÆ°Æ¡ng thá»©c thanh toÃ¡n khÃ´ng?',
        answer: 'Báº¡n chá»‰ cÃ³ thá»ƒ thay Ä‘á»•i phÆ°Æ¡ng thá»©c thanh toÃ¡n trÆ°á»›c khi hoÃ n táº¥t thanh toÃ¡n. Sau khi thanh toÃ¡n, báº¡n khÃ´ng thá»ƒ thay Ä‘á»•i.',
        keywords: ['Ä‘á»•i phÆ°Æ¡ng thá»©c', 'change payment', 'thay Ä‘á»•i thanh toÃ¡n'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'CÃ³ chÆ°Æ¡ng trÃ¬nh Æ°u Ä‘Ã£i cho sinh viÃªn khÃ´ng?',
        answer: 'CÃ³, sinh viÃªn sáº½ Ä‘Æ°á»£c giáº£m 10% khi xuáº¥t trÃ¬nh tháº» sinh viÃªn cÃ²n hiá»‡u lá»±c. Vui lÃ²ng táº£i áº£nh tháº» sinh viÃªn lÃªn tÃ i khoáº£n Ä‘á»ƒ Ä‘Æ°á»£c Ã¡p dá»¥ng.',
        keywords: ['Æ°u Ä‘Ã£i sinh viÃªn', 'student discount', 'giáº£m giÃ¡ sinh viÃªn'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'LÃ m tháº¿ nÃ o Ä‘á»ƒ sá»­ dá»¥ng mÃ£ giáº£m giÃ¡?',
        answer: 'Khi thanh toÃ¡n, báº¡n nháº­p mÃ£ giáº£m giÃ¡ vÃ o Ã´ "MÃ£ khuyáº¿n mÃ£i" vÃ  click "Ãp dá»¥ng". Há»‡ thá»‘ng sáº½ tá»± Ä‘á»™ng tÃ­nh giáº£m giÃ¡ cho báº¡n.',
        keywords: ['dÃ¹ng mÃ£', 'apply coupon', 'nháº­p voucher', 'sá»­ dá»¥ng giáº£m giÃ¡'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'Má»™t mÃ£ giáº£m giÃ¡ cÃ³ dÃ¹ng Ä‘Æ°á»£c nhiá»u láº§n khÃ´ng?',
        answer: 'Má»—i mÃ£ giáº£m giÃ¡ chá»‰ Ä‘Æ°á»£c sá»­ dá»¥ng 1 láº§n cho má»—i tÃ i khoáº£n, trá»« khi cÃ³ quy Ä‘á»‹nh khÃ¡c. Vui lÃ²ng xem Ä‘iá»u kiá»‡n sá»­ dá»¥ng cá»§a tá»«ng mÃ£.',
        keywords: ['mÃ£ dÃ¹ng nhiá»u láº§n', 'coupon usage', 'reuse voucher'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'CÃ³ Ä‘Æ°á»£c dÃ¹ng nhiá»u mÃ£ giáº£m giÃ¡ cÃ¹ng lÃºc khÃ´ng?',
        answer: 'KhÃ´ng, báº¡n chá»‰ cÃ³ thá»ƒ sá»­ dá»¥ng 1 mÃ£ giáº£m giÃ¡ cho má»—i Ä‘Æ¡n hÃ ng. HÃ£y chá»n mÃ£ cÃ³ giÃ¡ trá»‹ giáº£m nhiá»u nháº¥t.',
        keywords: ['nhiá»u mÃ£', 'multiple coupon', 'stack voucher'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'Táº¡i sao thanh toÃ¡n cá»§a tÃ´i bá»‹ tá»« chá»‘i?',
        answer: 'Thanh toÃ¡n cÃ³ thá»ƒ bá»‹ tá»« chá»‘i do: tÃ i khoáº£n/tháº» khÃ´ng Ä‘á»§ tiá»n, thÃ´ng tin tháº» sai, hoáº·c ngÃ¢n hÃ ng tá»« chá»‘i giao dá»‹ch. Vui lÃ²ng kiá»ƒm tra láº¡i hoáº·c thá»­ phÆ°Æ¡ng thá»©c khÃ¡c.',
        keywords: ['thanh toÃ¡n tháº¥t báº¡i', 'payment failed', 'bá»‹ tá»« chá»‘i', 'declined'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ xem lá»‹ch sá»­ thanh toÃ¡n?',
        answer: 'Báº¡n vÃ o "TÃ i khoáº£n cá»§a tÃ´i" > "Lá»‹ch sá»­ giao dá»‹ch" Ä‘á»ƒ xem táº¥t cáº£ cÃ¡c giao dá»‹ch thanh toÃ¡n vÃ  hoÃ n tiá»n.',
        keywords: ['lá»‹ch sá»­ thanh toÃ¡n', 'payment history', 'transaction history'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'CÃ³ Ä‘Æ°á»£c xuáº¥t hÃ³a Ä‘Æ¡n VAT khÃ´ng?',
        answer: 'CÃ³, náº¿u báº¡n cáº§n hÃ³a Ä‘Æ¡n VAT, vui lÃ²ng cung cáº¥p thÃ´ng tin cÃ´ng ty (tÃªn, mÃ£ sá»‘ thuáº¿, Ä‘á»‹a chá»‰) khi thanh toÃ¡n hoáº·c liÃªn há»‡ vá»›i chÃºng tÃ´i sau Ä‘Ã³.',
        keywords: ['hÃ³a Ä‘Æ¡n vat', 'invoice', 'hÃ³a Ä‘Æ¡n Ä‘á»', 'vat invoice'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'TÃ´i Ä‘Ã£ thanh toÃ¡n nhÆ°ng khÃ´ng nháº­n Ä‘Æ°á»£c xÃ¡c nháº­n?',
        answer: 'XÃ¡c nháº­n thanh toÃ¡n sáº½ Ä‘Æ°á»£c gá»­i qua email trong vÃ²ng 5-10 phÃºt. Náº¿u chÆ°a nháº­n Ä‘Æ°á»£c, vui lÃ²ng kiá»ƒm tra há»™p thÆ° spam hoáº·c liÃªn há»‡ vá»›i chÃºng tÃ´i.',
        keywords: ['khÃ´ng nháº­n xÃ¡c nháº­n', 'no confirmation', 'chÆ°a cÃ³ email'],
        category: 'payment',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ chuyá»ƒn khoáº£n trá»±c tiáº¿p khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ chuyá»ƒn khoáº£n trá»±c tiáº¿p qua ngÃ¢n hÃ ng. ThÃ´ng tin tÃ i khoáº£n sáº½ Ä‘Æ°á»£c hiá»ƒn thá»‹ khi báº¡n chá»n phÆ°Æ¡ng thá»©c "Chuyá»ƒn khoáº£n ngÃ¢n hÃ ng" khi thanh toÃ¡n.',
        keywords: ['chuyá»ƒn khoáº£n', 'bank transfer', 'banking', 'transfer'],
        category: 'payment',
        isActive: true,
    },

    // CÃ¢u há»i vá» tÃ i khoáº£n vÃ  báº£o máº­t (36-50)
    {
        question: 'LÃ m sao Ä‘á»ƒ Ä‘á»•i máº­t kháº©u?',
        answer: 'Báº¡n vÃ o "TÃ i khoáº£n cá»§a tÃ´i" > "CÃ i Ä‘áº·t báº£o máº­t" > "Äá»•i máº­t kháº©u", sau Ä‘Ã³ nháº­p máº­t kháº©u cÅ© vÃ  máº­t kháº©u má»›i.',
        keywords: ['Ä‘á»•i password', 'change password', 'Ä‘á»•i máº­t kháº©u', 'reset password'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'TÃ´i quÃªn máº­t kháº©u thÃ¬ lÃ m sao?',
        answer: 'Báº¡n click vÃ o "QuÃªn máº­t kháº©u" á»Ÿ trang Ä‘Äƒng nháº­p, nháº­p email Ä‘Ã£ Ä‘Äƒng kÃ½, chÃºng tÃ´i sáº½ gá»­i link Ä‘áº·t láº¡i máº­t kháº©u cho báº¡n.',
        keywords: ['quÃªn password', 'forgot password', 'khÃ´i phá»¥c máº­t kháº©u', 'recover'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ cáº­p nháº­t thÃ´ng tin cÃ¡ nhÃ¢n?',
        answer: 'Báº¡n vÃ o "TÃ i khoáº£n cá»§a tÃ´i" > "ThÃ´ng tin cÃ¡ nhÃ¢n", sau Ä‘Ã³ cáº­p nháº­t cÃ¡c thÃ´ng tin nhÆ° tÃªn, sá»‘ Ä‘iá»‡n thoáº¡i, Ä‘á»‹a chá»‰ vÃ  click "LÆ°u".',
        keywords: ['cáº­p nháº­t thÃ´ng tin', 'update profile', 'sá»­a thÃ´ng tin', 'edit info'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ Ä‘á»•i email Ä‘Äƒng kÃ½ khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ Ä‘á»•i email trong pháº§n "CÃ i Ä‘áº·t tÃ i khoáº£n". Báº¡n sáº½ cáº§n xÃ¡c thá»±c email má»›i báº±ng mÃ£ OTP Ä‘Æ°á»£c gá»­i Ä‘áº¿n email Ä‘Ã³.',
        keywords: ['Ä‘á»•i email', 'change email', 'email má»›i'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'ThÃ´ng tin cÃ¡ nhÃ¢n cá»§a tÃ´i cÃ³ Ä‘Æ°á»£c báº£o máº­t khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cam káº¿t báº£o máº­t thÃ´ng tin cÃ¡ nhÃ¢n cá»§a báº¡n theo chÃ­nh sÃ¡ch báº£o máº­t. ThÃ´ng tin cá»§a báº¡n Ä‘Æ°á»£c mÃ£ hÃ³a vÃ  khÃ´ng chia sáº» cho bÃªn thá»© ba.',
        keywords: ['báº£o máº­t', 'privacy', 'security', 'an toÃ n'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ xÃ³a tÃ i khoáº£n?',
        answer: 'Náº¿u báº¡n muá»‘n xÃ³a tÃ i khoáº£n, vui lÃ²ng liÃªn há»‡ vá»›i chÃºng tÃ´i qua email hoáº·c hotline. LÆ°u Ã½: sau khi xÃ³a, báº¡n sáº½ máº¥t toÃ n bá»™ dá»¯ liá»‡u vÃ  khÃ´ng thá»ƒ khÃ´i phá»¥c.',
        keywords: ['xÃ³a tÃ i khoáº£n', 'delete account', 'deactivate', 'remove account'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'Táº¡i sao tÃ i khoáº£n cá»§a tÃ´i bá»‹ khÃ³a?',
        answer: 'TÃ i khoáº£n cÃ³ thá»ƒ bá»‹ khÃ³a do: vi pháº¡m Ä‘iá»u khoáº£n sá»­ dá»¥ng, tráº£ sÃ¡ch muá»™n nhiá»u láº§n, hoáº·c lÃ m hÆ° há»ng sÃ¡ch. Vui lÃ²ng liÃªn há»‡ vá»›i chÃºng tÃ´i Ä‘á»ƒ Ä‘Æ°á»£c há»— trá»£.',
        keywords: ['tÃ i khoáº£n bá»‹ khÃ³a', 'account locked', 'suspended', 'banned'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ táº¡o nhiá»u tÃ i khoáº£n khÃ´ng?',
        answer: 'Má»—i ngÆ°á»i chá»‰ nÃªn cÃ³ 1 tÃ i khoáº£n. Viá»‡c táº¡o nhiá»u tÃ i khoáº£n Ä‘á»ƒ lá»£i dá»¥ng khuyáº¿n mÃ£i lÃ  vi pháº¡m Ä‘iá»u khoáº£n vÃ  cÃ³ thá»ƒ bá»‹ khÃ³a táº¥t cáº£ tÃ i khoáº£n.',
        keywords: ['nhiá»u tÃ i khoáº£n', 'multiple account', 'táº¡o tÃ i khoáº£n má»›i'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ xem lá»‹ch sá»­ thuÃª sÃ¡ch?',
        answer: 'Báº¡n vÃ o "TÃ i khoáº£n cá»§a tÃ´i" > "Lá»‹ch sá»­ thuÃª sÃ¡ch" Ä‘á»ƒ xem táº¥t cáº£ cÃ¡c Ä‘Æ¡n thuÃª sÃ¡ch Ä‘Ã£ hoÃ n thÃ nh vÃ  Ä‘ang thuÃª.',
        keywords: ['lá»‹ch sá»­ thuÃª', 'rental history', 'Ä‘Æ¡n hÃ ng cÅ©', 'order history'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ lÆ°u sÃ¡ch yÃªu thÃ­ch khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ click vÃ o biá»ƒu tÆ°á»£ng trÃ¡i tim á»Ÿ trang chi tiáº¿t sÃ¡ch Ä‘á»ƒ thÃªm vÃ o danh sÃ¡ch yÃªu thÃ­ch. Xem danh sÃ¡ch trong "TÃ i khoáº£n cá»§a tÃ´i" > "SÃ¡ch yÃªu thÃ­ch".',
        keywords: ['yÃªu thÃ­ch', 'favorite', 'wishlist', 'bookmark'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ nháº­n thÃ´ng bÃ¡o qua email khÃ´ng?',
        answer: 'CÃ³, báº¡n sáº½ nháº­n email thÃ´ng bÃ¡o vá»: xÃ¡c nháº­n Ä‘Æ¡n hÃ ng, nháº¯c nhá»Ÿ tráº£ sÃ¡ch, khuyáº¿n mÃ£i. Báº¡n cÃ³ thá»ƒ tÃ¹y chá»‰nh trong "CÃ i Ä‘áº·t thÃ´ng bÃ¡o".',
        keywords: ['thÃ´ng bÃ¡o email', 'notification', 'email alert'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ á»©ng dá»¥ng mobile khÃ´ng?',
        answer: 'Hiá»‡n táº¡i chÃºng tÃ´i chÆ°a cÃ³ á»©ng dá»¥ng mobile riÃªng. Tuy nhiÃªn, website Ä‘Æ°á»£c tá»‘i Æ°u cho mobile, báº¡n cÃ³ thá»ƒ truy cáº­p dá»… dÃ ng trÃªn Ä‘iá»‡n thoáº¡i.',
        keywords: ['app', 'mobile app', 'á»©ng dá»¥ng', 'ios', 'android'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ báº­t xÃ¡c thá»±c 2 bÆ°á»›c?',
        answer: 'Báº¡n vÃ o "CÃ i Ä‘áº·t báº£o máº­t" > "XÃ¡c thá»±c 2 bÆ°á»›c" vÃ  lÃ m theo hÆ°á»›ng dáº«n. TÃ­nh nÄƒng nÃ y giÃºp tÃ i khoáº£n cá»§a báº¡n an toÃ n hÆ¡n.',
        keywords: ['2fa', 'two factor', 'xÃ¡c thá»±c 2 bÆ°á»›c', 'authentication'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'Táº¡i sao tÃ´i khÃ´ng Ä‘Äƒng nháº­p Ä‘Æ°á»£c?',
        answer: 'CÃ³ thá»ƒ do: sai email/máº­t kháº©u, tÃ i khoáº£n chÆ°a kÃ­ch hoáº¡t, hoáº·c tÃ i khoáº£n bá»‹ khÃ³a. HÃ£y thá»­ Ä‘áº·t láº¡i máº­t kháº©u hoáº·c liÃªn há»‡ vá»›i chÃºng tÃ´i.',
        keywords: ['khÃ´ng Ä‘Äƒng nháº­p Ä‘Æ°á»£c', 'login failed', 'cant login', 'Ä‘Äƒng nháº­p lá»—i'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ kÃ­ch hoáº¡t tÃ i khoáº£n?',
        answer: 'Sau khi Ä‘Äƒng kÃ½, chÃºng tÃ´i sáº½ gá»­i email kÃ­ch hoáº¡t. Báº¡n click vÃ o link trong email Ä‘á»ƒ kÃ­ch hoáº¡t tÃ i khoáº£n. Náº¿u khÃ´ng nháº­n Ä‘Æ°á»£c, vui lÃ²ng liÃªn há»‡.',
        keywords: ['kÃ­ch hoáº¡t', 'activate', 'verify email', 'xÃ¡c thá»±c tÃ i khoáº£n'],
        category: 'general',
        isActive: true,
    },

    // CÃ¢u há»i vá» thuÃª vÃ  tráº£ sÃ¡ch (51-70)
    {
        question: 'Thá»i gian giao sÃ¡ch lÃ  bao lÃ¢u?',
        answer: 'Thá»i gian giao sÃ¡ch trong ná»™i thÃ nh lÃ  1-2 ngÃ y, ngoáº¡i thÃ nh lÃ  3-5 ngÃ y tÃ¹y khu vá»±c. Báº¡n cÃ³ thá»ƒ chá»n giao nhanh vá»›i phÃ­ bá»• sung.',
        keywords: ['thá»i gian giao', 'delivery time', 'bao lÃ¢u nháº­n sÃ¡ch', 'shipping time'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ chá»n thá»i gian giao hÃ ng khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ chá»n khung giá» giao hÃ ng mong muá»‘n (sÃ¡ng, chiá»u, tá»‘i) khi Ä‘áº·t hÃ ng. ChÃºng tÃ´i sáº½ cá»‘ gáº¯ng giao Ä‘Ãºng thá»i gian báº¡n chá»n.',
        keywords: ['chá»n giá» giao', 'delivery slot', 'thá»i gian nháº­n', 'appointment'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'Náº¿u tÃ´i khÃ´ng cÃ³ nhÃ  khi giao hÃ ng thÃ¬ sao?',
        answer: 'Shipper sáº½ gá»i Ä‘iá»‡n trÆ°á»›c khi giao. Náº¿u báº¡n khÃ´ng cÃ³ nhÃ , báº¡n cÃ³ thá»ƒ háº¹n láº¡i giá» giao khÃ¡c hoáº·c nhá» ngÆ°á»i thÃ¢n nháº­n há»™.',
        keywords: ['khÃ´ng nháº­n Ä‘Æ°á»£c', 'váº¯ng nhÃ ', 'absent', 'missed delivery'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ Ä‘áº¿n thÆ° viá»‡n láº¥y sÃ¡ch trá»±c tiáº¿p khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ chá»n "Tá»± Ä‘áº¿n láº¥y" khi thanh toÃ¡n vÃ  Ä‘áº¿n Ä‘á»‹a chá»‰ thÆ° viá»‡n Ä‘á»ƒ nháº­n sÃ¡ch. Sáº½ miá»…n phÃ­ váº­n chuyá»ƒn.',
        keywords: ['tá»± láº¥y', 'pickup', 'Ä‘áº¿n láº¥y', 'self pickup'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'Äá»‹a chá»‰ thÆ° viá»‡n á»Ÿ Ä‘Ã¢u?',
        answer: 'ThÆ° viá»‡n chÃºng tÃ´i táº¡i: 123 ÄÆ°á»ng ABC, Quáº­n XYZ, ThÃ nh phá»‘. Giá» má»Ÿ cá»­a: 8h00-22h00 tá»« thá»© 2 Ä‘áº¿n chá»§ nháº­t.',
        keywords: ['Ä‘á»‹a chá»‰', 'address', 'location', 'thÆ° viá»‡n á»Ÿ Ä‘Ã¢u'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'Giá» lÃ m viá»‡c cá»§a thÆ° viá»‡n?',
        answer: 'ThÆ° viá»‡n má»Ÿ cá»­a tá»« 8h00-22h00 táº¥t cáº£ cÃ¡c ngÃ y trong tuáº§n, ká»ƒ cáº£ ngÃ y lá»… vÃ  chá»§ nháº­t.',
        keywords: ['giá» má»Ÿ cá»­a', 'opening hours', 'working time', 'giá» lÃ m viá»‡c'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ gia háº¡n thÃªm thá»i gian thuÃª khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ gia háº¡n trÆ°á»›c khi háº¿t háº¡n. VÃ o "ÄÆ¡n hÃ ng cá»§a tÃ´i", chá»n Ä‘Æ¡n cáº§n gia háº¡n vÃ  click "Gia háº¡n". PhÃ­ gia háº¡n = giÃ¡ thuÃª/ngÃ y x sá»‘ ngÃ y gia háº¡n.',
        keywords: ['gia háº¡n', 'extend', 'renew', 'mÆ°á»£n thÃªm'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ tráº£ sÃ¡ch sá»›m hÆ¡n khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ tráº£ sÃ¡ch sá»›m hÆ¡n ngÃ y háº¹n. Tuy nhiÃªn, chÃºng tÃ´i khÃ´ng hoÃ n láº¡i tiá»n cho sá»‘ ngÃ y chÆ°a sá»­ dá»¥ng.',
        keywords: ['tráº£ sá»›m', 'early return', 'tráº£ trÆ°á»›c háº¡n'],
        category: 'return',
        isActive: true,
    },
    {
        question: 'Náº¿u sÃ¡ch bá»‹ máº¥t thÃ¬ sao?',
        answer: 'Náº¿u sÃ¡ch bá»‹ máº¥t, báº¡n cáº§n bá»“i thÆ°á»ng theo giÃ¡ trá»‹ sÃ¡ch (thÆ°á»ng gáº¥p 2-3 láº§n giÃ¡ bÃ¬a). Tiá»n cá»c sáº½ Ä‘Æ°á»£c trá»« vÃ o sá»‘ tiá»n bá»“i thÆ°á»ng.',
        keywords: ['sÃ¡ch máº¥t', 'lost book', 'bá»‹ máº¥t', 'bá»“i thÆ°á»ng'],
        category: 'return',
        isActive: true,
    },
    {
        question: 'Náº¿u tÃ´i lÃ m há»ng sÃ¡ch thÃ¬ sao?',
        answer: 'TÃ¹y má»©c Ä‘á»™ hÆ° há»ng: hÆ° há»ng nháº¹ (gáº¥p gÃ³c, nhÃ u trang) pháº¡t 10,000-30,000â‚«; hÆ° há»ng náº·ng (rÃ¡ch, Æ°á»›t, viáº¿t báº­y) pháº¡t 50-100% giÃ¡ sÃ¡ch.',
        keywords: ['sÃ¡ch há»ng', 'damaged book', 'lÃ m hÆ°', 'rÃ¡ch sÃ¡ch'],
        category: 'return',
        isActive: true,
    },
    {
        question: 'CÃ³ Ä‘Æ°á»£c Ä‘á»•i sÃ¡ch sau khi thuÃª khÃ´ng?',
        answer: 'Náº¿u sÃ¡ch bá»‹ lá»—i hoáº·c khÃ´ng Ä‘Ãºng nhÆ° mÃ´ táº£, báº¡n cÃ³ thá»ƒ Ä‘á»•i trong vÃ²ng 24h sau khi nháº­n. Náº¿u chá»‰ Ä‘Æ¡n giáº£n khÃ´ng thÃ­ch, chÃºng tÃ´i khÃ´ng há»— trá»£ Ä‘á»•i.',
        keywords: ['Ä‘á»•i sÃ¡ch', 'exchange', 'swap book', 'thay sÃ¡ch'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ theo dÃµi Ä‘Æ¡n hÃ ng?',
        answer: 'Báº¡n vÃ o "ÄÆ¡n hÃ ng cá»§a tÃ´i" Ä‘á»ƒ xem tráº¡ng thÃ¡i Ä‘Æ¡n hÃ ng. ChÃºng tÃ´i cÅ©ng gá»­i thÃ´ng bÃ¡o qua email vÃ  SMS khi cÃ³ cáº­p nháº­t.',
        keywords: ['theo dÃµi Ä‘Æ¡n', 'track order', 'tráº¡ng thÃ¡i Ä‘Æ¡n', 'order status'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'ÄÆ¡n hÃ ng Ä‘Ã£ Ä‘Æ°á»£c xÃ¡c nháº­n nghÄ©a lÃ  gÃ¬?',
        answer: 'NghÄ©a lÃ  chÃºng tÃ´i Ä‘Ã£ nháº­n Ä‘Æ°á»£c Ä‘Æ¡n hÃ ng vÃ  thanh toÃ¡n cá»§a báº¡n. ChÃºng tÃ´i sáº½ chuáº©n bá»‹ sÃ¡ch vÃ  giao trong thá»i gian sá»›m nháº¥t.',
        keywords: ['Ä‘Æ¡n hÃ ng xÃ¡c nháº­n', 'confirmed order', 'order confirmed'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ thay Ä‘á»•i Ä‘á»‹a chá»‰ giao hÃ ng khÃ´ng?',
        answer: 'Báº¡n cÃ³ thá»ƒ thay Ä‘á»•i Ä‘á»‹a chá»‰ trÆ°á»›c khi Ä‘Æ¡n hÃ ng Ä‘Æ°á»£c giao cho shipper. Sau Ä‘Ã³, vui lÃ²ng liÃªn há»‡ hotline Ä‘á»ƒ Ä‘Æ°á»£c há»— trá»£.',
        keywords: ['Ä‘á»•i Ä‘á»‹a chá»‰', 'change address', 'Ä‘á»‹a chá»‰ má»›i'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'Nháº¯c nhá»Ÿ tráº£ sÃ¡ch nhÆ° tháº¿ nÃ o?',
        answer: 'ChÃºng tÃ´i sáº½ gá»­i email vÃ  SMS nháº¯c nhá»Ÿ trÆ°á»›c 2 ngÃ y vÃ  trÆ°á»›c 1 ngÃ y khi Ä‘áº¿n háº¡n tráº£ sÃ¡ch. Báº¡n cÅ©ng cÃ³ thá»ƒ xem trong tÃ i khoáº£n.',
        keywords: ['nháº¯c tráº£ sÃ¡ch', 'reminder', 'thÃ´ng bÃ¡o tráº£', 'due date'],
        category: 'return',
        isActive: true,
    },
    {
        question: 'CÃ³ dá»‹ch vá»¥ láº¥y sÃ¡ch táº­n nÆ¡i khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ dá»‹ch vá»¥ Ä‘áº¿n láº¥y sÃ¡ch táº­n nÆ¡i khi báº¡n tráº£. PhÃ­ dá»‹ch vá»¥ lÃ  15,000â‚«. Báº¡n cÃ³ thá»ƒ Ä‘áº·t lá»‹ch láº¥y sÃ¡ch trong tÃ i khoáº£n.',
        keywords: ['láº¥y sÃ¡ch táº­n nÆ¡i', 'pickup service', 'Ä‘áº¿n láº¥y', 'return pickup'],
        category: 'return',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ tráº£ sÃ¡ch á»Ÿ Ä‘á»‹a chá»‰ khÃ¡c khÃ´ng?',
        answer: 'Báº¡n cÃ³ thá»ƒ tráº£ sÃ¡ch táº¡i thÆ° viá»‡n hoáº·c gá»­i qua dá»‹ch vá»¥ váº­n chuyá»ƒn. Hiá»‡n khÃ´ng há»— trá»£ tráº£ sÃ¡ch táº¡i Ä‘iá»ƒm khÃ¡c.',
        keywords: ['tráº£ á»Ÿ Ä‘Ã¢u', 'return location', 'Ä‘á»‹a Ä‘iá»ƒm tráº£'],
        category: 'return',
        isActive: true,
    },
    {
        question: 'CÃ³ chÆ°Æ¡ng trÃ¬nh thÃ nh viÃªn thÃ¢n thiáº¿t khÃ´ng?',
        answer: 'CÃ³, khÃ¡ch hÃ ng tÃ­ch Ä‘iá»ƒm má»—i khi thuÃª sÃ¡ch. Äá»§ Ä‘iá»ƒm sáº½ Ä‘Æ°á»£c giáº£m giÃ¡, miá»…n phÃ­ ship, hoáº·c quÃ  táº·ng. Xem chi tiáº¿t trong "ChÆ°Æ¡ng trÃ¬nh thÃ nh viÃªn".',
        keywords: ['thÃ nh viÃªn', 'membership', 'loyalty', 'tÃ­ch Ä‘iá»ƒm'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'Äiá»ƒm thÃ nh viÃªn tÃ­nh nhÆ° tháº¿ nÃ o?',
        answer: 'Má»—i 10,000â‚« chi tiÃªu = 1 Ä‘iá»ƒm. 100 Ä‘iá»ƒm = 1 voucher giáº£m giÃ¡ 50,000â‚«. Äiá»ƒm cÃ³ hiá»‡u lá»±c 1 nÄƒm ká»ƒ tá»« ngÃ y tÃ­ch.',
        keywords: ['tÃ­ch Ä‘iá»ƒm', 'points', 'loyalty points', 'Ä‘iá»ƒm thÆ°á»Ÿng'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ Ä‘Æ°á»£c táº·ng sÃ¡ch cho báº¡n bÃ¨ khÃ´ng?',
        answer: 'Hiá»‡n táº¡i chÆ°a há»— trá»£ tÃ­nh nÄƒng táº·ng sÃ¡ch. Báº¡n cÃ³ thá»ƒ mua voucher Ä‘á»ƒ táº·ng báº¡n bÃ¨, há» cÃ³ thá»ƒ dÃ¹ng voucher Ä‘á»ƒ thuÃª sÃ¡ch.',
        keywords: ['táº·ng sÃ¡ch', 'gift', 'quÃ  táº·ng', 'gift book'],
        category: 'general',
        isActive: true,
    },

    // CÃ¢u há»i vá» há»— trá»£ vÃ  khiáº¿u náº¡i (71-85)
    {
        question: 'LÃ m sao Ä‘á»ƒ khiáº¿u náº¡i vá» dá»‹ch vá»¥?',
        answer: 'Báº¡n cÃ³ thá»ƒ gá»­i khiáº¿u náº¡i qua: 1) Form "LiÃªn há»‡" trÃªn website, 2) Email: support@dav.edu.vn, 3) Hotline: 0123-456-789. ChÃºng tÃ´i sáº½ pháº£n há»“i trong 24h.',
        keywords: ['khiáº¿u náº¡i', 'complaint', 'pháº£n Ã¡nh', 'report issue'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'Thá»i gian pháº£n há»“i cá»§a bá»™ pháº­n há»— trá»£?',
        answer: 'ChÃºng tÃ´i pháº£n há»“i email trong vÃ²ng 24h, chat/hotline trong giá» hÃ nh chÃ­nh. CÃ¡c váº¥n Ä‘á» kháº©n cáº¥p sáº½ Ä‘Æ°á»£c Æ°u tiÃªn xá»­ lÃ½.',
        keywords: ['thá»i gian pháº£n há»“i', 'response time', 'support time'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ há»— trá»£ qua chat khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ chat trá»±c tiáº¿p vá»›i chatbot nÃ y hoáº·c vá»›i nhÃ¢n viÃªn trong giá» hÃ nh chÃ­nh (8h-22h) báº±ng cÃ¡ch click "Chat vá»›i nhÃ¢n viÃªn".',
        keywords: ['chat', 'live chat', 'chat trá»±c tuyáº¿n', 'online chat'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ gÃ³p Ã½ vá» website khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i ráº¥t hoan nghÃªnh má»i gÃ³p Ã½ Ä‘á»ƒ cáº£i thiá»‡n dá»‹ch vá»¥. Báº¡n cÃ³ thá»ƒ gá»­i gÃ³p Ã½ qua form "GÃ³p Ã½" hoáº·c email feedback@dav.edu.vn.',
        keywords: ['gÃ³p Ã½', 'feedback', 'suggestion', 'Ä‘á» xuáº¥t'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ Ä‘á» xuáº¥t thÃªm sÃ¡ch má»›i khÃ´ng?',
        answer: 'CÃ³, náº¿u báº¡n muá»‘n chÃºng tÃ´i nháº­p thÃªm sÃ¡ch nÃ o, hÃ£y gá»­i Ä‘á» xuáº¥t qua form "Äá» xuáº¥t sÃ¡ch" trÃªn website. ChÃºng tÃ´i sáº½ xem xÃ©t vÃ  cáº­p nháº­t.',
        keywords: ['Ä‘á» xuáº¥t sÃ¡ch', 'request book', 'suggest book', 'book request'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'Website bá»‹ lá»—i thÃ¬ lÃ m sao?',
        answer: 'Náº¿u báº¡n gáº·p lá»—i ká»¹ thuáº­t, vui lÃ²ng chá»¥p mÃ n hÃ¬nh vÃ  gá»­i cho chÃºng tÃ´i qua email support@dav.edu.vn kÃ¨m mÃ´ táº£ chi tiáº¿t. ChÃºng tÃ´i sáº½ kháº¯c phá»¥c sá»›m nháº¥t.',
        keywords: ['website lá»—i', 'bug', 'error', 'technical issue'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ video hÆ°á»›ng dáº«n sá»­ dá»¥ng khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ xem video hÆ°á»›ng dáº«n chi tiáº¿t trong má»¥c "HÆ°á»›ng dáº«n" trÃªn website hoáº·c trÃªn kÃªnh YouTube cá»§a chÃºng tÃ´i.',
        keywords: ['video hÆ°á»›ng dáº«n', 'tutorial', 'guide video', 'how to'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ FAQ chi tiáº¿t hÆ¡n khÃ´ng?',
        answer: 'CÃ³, báº¡n cÃ³ thá»ƒ xem táº¥t cáº£ FAQ trong má»¥c "CÃ¢u há»i thÆ°á»ng gáº·p" trÃªn website. Náº¿u khÃ´ng tÃ¬m tháº¥y cÃ¢u tráº£ lá»i, hÃ£y liÃªn há»‡ vá»›i chÃºng tÃ´i.',
        keywords: ['faq', 'cÃ¢u há»i thÆ°á»ng gáº·p', 'help center', 'knowledge base'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ chÆ°Æ¡ng trÃ¬nh giá»›i thiá»‡u báº¡n bÃ¨ khÃ´ng?',
        answer: 'CÃ³, giá»›i thiá»‡u báº¡n bÃ¨ Ä‘Äƒng kÃ½ vÃ  thuÃª sÃ¡ch, cáº£ hai sáº½ nháº­n mÃ£ giáº£m 20%. Xem chi tiáº¿t trong "ChÆ°Æ¡ng trÃ¬nh giá»›i thiá»‡u".',
        keywords: ['giá»›i thiá»‡u', 'referral', 'invite friend', 'refer'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'LÃ m sao Ä‘á»ƒ Ä‘Æ°á»£c há»— trá»£ Æ°u tiÃªn?',
        answer: 'ThÃ nh viÃªn VIP (thuÃª tá»« 50 cuá»‘n/nÄƒm) sáº½ Ä‘Æ°á»£c há»— trá»£ Æ°u tiÃªn, hotline riÃªng, vÃ  nhiá»u quyá»n lá»£i khÃ¡c. Xem chi tiáº¿t trong "ThÃ nh viÃªn VIP".',
        keywords: ['vip', 'priority', 'Æ°u tiÃªn', 'premium'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ chÃ­nh sÃ¡ch báº£o hÃ nh khÃ´ng?',
        answer: 'ChÃºng tÃ´i Ä‘áº£m báº£o cháº¥t lÆ°á»£ng sÃ¡ch khi giao. Náº¿u sÃ¡ch cÃ³ váº¥n Ä‘á» trong 24h Ä‘áº§u (khÃ´ng do lá»—i ngÆ°á»i dÃ¹ng), chÃºng tÃ´i sáº½ Ä‘á»•i miá»…n phÃ­.',
        keywords: ['báº£o hÃ nh', 'warranty', 'guarantee', 'quality'],
        category: 'general',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ yÃªu cáº§u dá»n sÃ¡ch trÆ°á»›c khi giao khÃ´ng?',
        answer: 'Táº¥t cáº£ sÃ¡ch Ä‘á»u Ä‘Æ°á»£c kiá»ƒm tra vÃ  vá»‡ sinh trÆ°á»›c khi giao. Náº¿u báº¡n cÃ³ yÃªu cáº§u Ä‘áº·c biá»‡t, vui lÃ²ng ghi chÃº khi Ä‘áº·t hÃ ng.',
        keywords: ['vá»‡ sinh sÃ¡ch', 'clean book', 'sáº¡ch sáº½'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ dá»‹ch vá»¥ Ä‘Ã³ng gÃ³i quÃ  khÃ´ng?',
        answer: 'Hiá»‡n chÆ°a cÃ³ dá»‹ch vá»¥ Ä‘Ã³ng gÃ³i quÃ . SÃ¡ch sáº½ Ä‘Æ°á»£c Ä‘Ã³ng gÃ³i cáº©n tháº­n trong tÃºi/há»™p chuyÃªn dá»¥ng Ä‘á»ƒ báº£o vá»‡ trong quÃ¡ trÃ¬nh váº­n chuyá»ƒn.',
        keywords: ['Ä‘Ã³ng gÃ³i', 'packaging', 'gift wrap', 'wrapping'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ thá»ƒ thuÃª sÃ¡ch cho tá»• chá»©c khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ gÃ³i dá»‹ch vá»¥ cho tá»• chá»©c, cÃ´ng ty, trÆ°á»ng há»c. Vui lÃ²ng liÃªn há»‡ qua email enterprise@dav.edu.vn Ä‘á»ƒ Ä‘Æ°á»£c tÆ° váº¥n.',
        keywords: ['thuÃª cho cÃ´ng ty', 'corporate', 'organization', 'bulk rental'],
        category: 'rental',
        isActive: true,
    },
    {
        question: 'CÃ³ chÆ°Æ¡ng trÃ¬nh Ä‘á»c sÃ¡ch cá»™ng Ä‘á»“ng khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i thÆ°á»ng xuyÃªn tá»• chá»©c cÃ¡c buá»•i Ä‘á»c sÃ¡ch, review sÃ¡ch, gáº·p gá»¡ tÃ¡c giáº£. Theo dÃµi fanpage Ä‘á»ƒ cáº­p nháº­t thÃ´ng tin.',
        keywords: ['sá»± kiá»‡n', 'event', 'cá»™ng Ä‘á»“ng', 'book club'],
        category: 'general',
        isActive: true,
    },

    // CÃ¢u há»i vá» thá»ƒ loáº¡i vÃ  ná»™i dung sÃ¡ch Ä‘áº·c biá»‡t (86-100)
    {
        question: 'CÃ³ sÃ¡ch vá» triáº¿t há»c khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u sÃ¡ch triáº¿t há»c tá»« ÄÃ´ng Ä‘áº¿n TÃ¢y, tá»« cá»• Ä‘iá»ƒn Ä‘áº¿n hiá»‡n Ä‘áº¡i. Xem trong danh má»¥c "Triáº¿t há»c".',
        keywords: ['triáº¿t há»c', 'philosophy', 'sÃ¡ch triáº¿t'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch há»c tiáº¿ng Anh khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u sÃ¡ch há»c tiáº¿ng Anh: IELTS, TOEIC, giao tiáº¿p, ngá»¯ phÃ¡p, tá»« vá»±ng. Xem trong danh má»¥c "Há»c ngoáº¡i ngá»¯".',
        keywords: ['há»c tiáº¿ng anh', 'english learning', 'ielts', 'toeic'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch náº¥u Äƒn khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u sÃ¡ch dáº¡y náº¥u Äƒn cÃ¡c mÃ³n Viá»‡t Nam vÃ  quá»‘c táº¿. Xem trong danh má»¥c "áº¨m thá»±c".',
        keywords: ['sÃ¡ch náº¥u Äƒn', 'cookbook', 'recipe', 'mÃ³n Äƒn'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ tiá»ƒu thuyáº¿t nÆ°á»›c ngoÃ i khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u tiá»ƒu thuyáº¿t Ä‘Æ°á»£c dá»‹ch tá»« cÃ¡c ngÃ´n ngá»¯ nhÆ° Anh, PhÃ¡p, Nháº­t, HÃ n... Xem trong danh má»¥c "VÄƒn há»c nÆ°á»›c ngoÃ i".',
        keywords: ['tiá»ƒu thuyáº¿t nÆ°á»›c ngoÃ i', 'foreign novel', 'translated book'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» nghá»‡ thuáº­t khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch vá» há»™i há»a, nhiáº¿p áº£nh, Ä‘iÃªu kháº¯c, kiáº¿n trÃºc, Ã¢m nháº¡c vÃ  cÃ¡c loáº¡i hÃ¬nh nghá»‡ thuáº­t khÃ¡c.',
        keywords: ['nghá»‡ thuáº­t', 'art', 'painting', 'photography'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» thá»ƒ thao khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch vá» cÃ¡c mÃ´n thá»ƒ thao, luyá»‡n táº­p, dinh dÆ°á»¡ng, vÃ  tiá»ƒu sá»­ váº­n Ä‘á»™ng viÃªn ná»•i tiáº¿ng.',
        keywords: ['thá»ƒ thao', 'sports', 'fitness', 'gym'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» du lá»‹ch khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch hÆ°á»›ng dáº«n du lá»‹ch cÃ¡c Ä‘á»‹a Ä‘iá»ƒm trong vÃ  ngoÃ i nÆ°á»›c, cáº©m nang phÆ°á»£t, vÃ  sÃ¡ch áº£nh du lá»‹ch.',
        keywords: ['du lá»‹ch', 'travel', 'guide book', 'phÆ°á»£t'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» y há»c khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch y há»c Ä‘áº¡i cÆ°Æ¡ng, chÄƒm sÃ³c sá»©c khá»e, bá»‡nh há»c, vÃ  sÃ¡ch chuyÃªn ngÃ nh cho sinh viÃªn y.',
        keywords: ['y há»c', 'medical', 'health', 'sá»©c khá»e'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» luáº­t phÃ¡p khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch vá» luáº­t dÃ¢n sá»±, luáº­t hÃ¬nh sá»±, luáº­t kinh doanh, vÃ  cÃ¡c vÄƒn báº£n phÃ¡p luáº­t. Xem trong danh má»¥c "Luáº­t".',
        keywords: ['luáº­t', 'law', 'legal', 'phÃ¡p luáº­t'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» mÃ´i trÆ°á»ng khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch vá» báº£o vá»‡ mÃ´i trÆ°á»ng, biáº¿n Ä‘á»•i khÃ­ háº­u, sinh thÃ¡i há»c, vÃ  phÃ¡t triá»ƒn bá»n vá»¯ng.',
        keywords: ['mÃ´i trÆ°á»ng', 'environment', 'ecology', 'climate'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» Ã¢m nháº¡c khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch dáº¡y nháº¡c cá»¥, lÃ½ thuyáº¿t Ã¢m nháº¡c, tiá»ƒu sá»­ nháº¡c sÄ©, vÃ  sÃ¡ch vá» cÃ¡c thá»ƒ loáº¡i Ã¢m nháº¡c.',
        keywords: ['Ã¢m nháº¡c', 'music', 'nháº¡c cá»¥', 'instrument'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» khoa há»c viá»…n tÆ°á»Ÿng khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ nhiá»u tÃ¡c pháº©m sci-fi ná»•i tiáº¿ng cá»§a cÃ¡c tÃ¡c giáº£ trong vÃ  ngoÃ i nÆ°á»›c. Xem trong danh má»¥c "Khoa há»c viá»…n tÆ°á»Ÿng".',
        keywords: ['sci-fi', 'science fiction', 'viá»…n tÆ°á»Ÿng', 'khoa há»c'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch kinh dá»‹ khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ bá»™ sÆ°u táº­p truyá»‡n kinh dá»‹, thriller, bÃ­ áº©n tá»« nhiá»u tÃ¡c giáº£ ná»•i tiáº¿ng. Xem trong danh má»¥c "Kinh dá»‹".',
        keywords: ['kinh dá»‹', 'horror', 'thriller', 'mystery'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» tÃ´n giÃ¡o khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch vá» cÃ¡c tÃ´n giÃ¡o: Pháº­t giÃ¡o, ThiÃªn ChÃºa giÃ¡o, Há»“i giÃ¡o, vÃ  cÃ¡c tÃ­n ngÆ°á»¡ng khÃ¡c.',
        keywords: ['tÃ´n giÃ¡o', 'religion', 'pháº­t giÃ¡o', 'christian'],
        category: 'product',
        isActive: true,
    },
    {
        question: 'CÃ³ sÃ¡ch vá» thiÃªn vÄƒn há»c khÃ´ng?',
        answer: 'CÃ³, chÃºng tÃ´i cÃ³ sÃ¡ch vá» vÅ© trá»¥, hÃ nh tinh, ngÃ´i sao, vÃ  cÃ¡c khÃ¡m phÃ¡ thiÃªn vÄƒn há»c hiá»‡n Ä‘áº¡i.',
        keywords: ['thiÃªn vÄƒn', 'astronomy', 'vÅ© trá»¥', 'space'],
        category: 'product',
        isActive: true,
    },
];

const seed100FAQs = async () => {
    try {
        // ThÃªm dá»¯ liá»‡u má»›i (khÃ´ng xÃ³a dá»¯ liá»‡u cÅ©)
        const result = await FAQ.insertMany(additionalFAQs);
        console.log(`âœ… ÄÃ£ thÃªm thÃ nh cÃ´ng ${result.length} cÃ¢u há»i FAQ má»›i!`);

        // Äáº¿m tá»•ng sá»‘ FAQ
        const totalCount = await FAQ.countDocuments();
        console.log(`ðŸ“Š Tá»•ng sá»‘ FAQ trong database: ${totalCount}`);

        console.log('\nðŸŽ‰ Seed data hoÃ n táº¥t!');
        process.exit(0);
    } catch (error) {
        console.error('âŒ Lá»—i khi seed data:', error);
        process.exit(1);
    }
};

seed100FAQs();

